version: '2'

services:
  app:
    build: .
    env_file: .env
    depends_on: [redis]

  redis:
    image: redis
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

volumes:
  redis:
